jobs:
  build:
    docker:
      - image: evillhood/arch-builder:latest
    steps:
      - run: |
          pwd
          cd /data
          pwd          
          git clone https://github.com/enree/shakespear.git
          cd shakespear
          cmake .
